# Generated by Django 3.2.5 on 2021-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Pedido', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Correo', models.EmailField(max_length=254)),
                ('Fecha', models.DateField()),
                ('Entregado', models.BooleanField()),
                ('Comentario', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Producto', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Stock', models.IntegerField()),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
