# Generated by Django 3.2.5 on 2021-09-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_contacto', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Correo', models.EmailField(max_length=254)),
                ('Tema', models.CharField(max_length=30)),
                ('Mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
